{{- if and .Values.dagProcessor.enabled .Values.dagProcessor.podDisruptionBudget.enabled (semverCompare ">=2.3.0" (include "airflow.version" .)) }}
apiVersion: {{ .Values.dagProcessor.podDisruptionBudget.apiVersion }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "airflow.fullname" . }}-dag-processor
  labels:
    app: {{ include "airflow.labels.app" . }}
    component: dag-processor
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.dagProcessor.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.dagProcessor.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  {{- if .Values.dagProcessor.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.dagProcessor.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "airflow.labels.app" . }}
      component: dag_processor
      release: {{ .Release.Name }}
{{- end }}
