{{- if and .Values.dagProcessor.enabled .Values.serviceMonitor.enabled (semverCompare ">=2.3.0" (include "airflow.version" .)) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "airflow.fullname" . }}-dag-processor
  labels:
    app: {{ include "airflow.labels.app" . }}
    component: dag-processor
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.serviceMonitor.selector }}
    {{- toYaml .Values.serviceMonitor.selector | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ include "airflow.labels.app" . }}
      component: dag-processor
      release: {{ .Release.Name }}
  endpoints:
    - port: dag-processor
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
