apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-jwt-secret" (include "airflow.fullname" .) }}
  labels:
    tier: airflow
    component: api-server
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.airflow.jwtSecretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  jwt-secret: {{ (.Values.airflow.jwtSecret) | default (randAlphaNum 32) | b64enc | quote }}
