apiVersion: v2
description: Airflow Helm Chart (User Community) - the standard way to deploy Apache Airflow on Kubernetes with Helm
name: airflow
type: application
version: 9.0.0
appVersion: 2.8.4
icon: https://avatars.githubusercontent.com/u/71061241
home: https://github.com/airflow-helm/charts/tree/main/charts/airflow
maintainers:
  - name: thesuperzapper
    url: https://github.com/thesuperzapper
sources:
  - https://github.com/airflow-helm/charts/tree/main/charts/airflow
keywords:
  - airflow
  - dag
  - workflow
dependencies:
  - name: postgresql
    version: 12.12.10
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: redis
    version: 18.19.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
