name: release image / postgresql-bitnami-11-alpine

on:
  push:
    branches:
      - main
    paths:
      - images/postgresql-bitnami/11/alpine/VERSION
      - .github/workflows/release-image--postgresql-bitnami-11-alpine.yaml

jobs:
  call_workflow:
    uses: ./.github/workflows/_release-image.yaml
    with:
      folder_path: images/postgresql-bitnami/11/alpine

      image_title: postgresql-bitnami
      image_description: the postgresql-bitnami image for the user-community airflow helm chart

      image_flavor: alpine
      image_flavor_is_primary: true

      tag_with_latest: true
      tag_with_major_version: true

      build_platforms: |
        linux/amd64
        linux/arm64
