# Test values for git-sync v4 with new features
# This file tests git-sync v4-specific functionality

airflow:
  image:
    repository: apache/airflow
    tag: 3.1.0

  executors: [KubernetesExecutor]

  config:
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"

dags:
  # Use git-sync v4 with new features
  gitSync:
    enabled: true
    image:
      tag: v4.5.0
    repo: "https://github.com/apache/airflow.git"

    # v4-specific: Use unified ref instead of branch + revision
    ref: "3.1.0"

    # v4-specific: Use Go duration format for period
    period: "30s"

    # v4-specific: Use Go duration format for period
    syncTimeout: "120s"

    # Use shallow clone (v4 default)
    depth: 1

    # v4-specific: Enable group-writable permissions
    groupWrite: true

    # Path to DAGs within the repo
    repoSubPath: "airflow-core/src/airflow/example_dags"

scheduler:
  replicas: 1

apiServer:
  replicas: 1

dagProcessor:
  enabled: true
  replicas: 1

workers:
  enabled: false

flower:
  enabled: false

postgresql:
  enabled: true

redis:
  enabled: false
